var SELECTORS = {
        ADD_DISCUSSION: '#newdiscussionform',
        ADD_DISCUSSION_TARGET: '.hsuforum-add-discussion-target',
        ALL_FORMS: '.hsuforum-reply-wrapper form',
        CONTAINER: '.mod_hsuforum_posts_container',
        CONTAINER_LINKS: '.mod_hsuforum_posts_container a',
        DISCUSSION: '.hsuforum-thread-article',
        DISCUSSIONS: '.hsuforum-threads-wrapper',
        DISCUSSION_BY_ID: '.hsuforum-thread-article[data-discussionid="%d"]',
        DISCUSSION_CLOSE: '.hsuforum-thread-nav .close',
        DISCUSSION_COUNT: '.hsuforum-discussion-count',
        DISCUSSION_NAV_LINKS: '.hsuforum-thread-nav a',
        DISCUSSION_NEXT: '.hsuforum-thread-nav .next',
        DISCUSSION_PREV: '.hsuforum-thread-nav .prev',
        DISCUSSION_TARGET: '.hsuforum-new-discussion-target',
        DISCUSSION_TEMPLATE: '#hsuforum-discussion-template',
        DISCUSSION_VIEW: '.hsuforum-thread-view',
        FORM_ADVANCED: '.hsuforum-use-advanced',
        FORM_DISCUSSION: '.hsuforum-discussion',
        FORM_REPLY: '.hsuforum-reply',
        FORM_REPLY_WRAPPER: '.hsuforum-reply-wrapper',
        INPUT_FORUM: 'input[name="forum"]',
        INPUT_MESSAGE: 'textarea[name="message"]',
        INPUT_REPLY: 'input[name="reply"]',
        INPUT_SUBJECT: 'input[name="subject"]',
        LOAD_MORE: '.hsuforum-threads-load-more',
        LOAD_TARGET: '.hsuforum-threads-load-target',
        NO_DISCUSSIONS: '.forumnodiscuss',
        NOTIFICATION: '.hsuforum-notification',
        OPTIONS_TO_PROCESS: '.hsuforum-options-menu.unprocessed',
        PLACEHOLDER: '.thread-replies-placeholder',
        POSTS: '.hsuforum-thread-replies',
        POST_BY_ID: '.hsuforum-post-target[data-postid="%d"]',
        POST_TARGET: '.hsuforum-post-target',
        RATE: '.forum-post-rating',
        RATE_POPUP: '.forum-post-rating a',
        REPLY_TEMPLATE: '#hsuforum-reply-template',
        SEARCH_PAGE: '#page-mod-hsuforum-search',
        VALIDATION_ERRORS: '.hsuforum-validation-errors',
        VIEW_POSTS: '.hsuforum-view-posts'
    },
    EVENTS = {
        DISCUSSION_CREATED: 'discussion:created',
        POST_CREATED: 'post:created',
        POST_DELETE: 'post:delete',
        POST_DELETED: 'post:deleted'
    };

M.mod_hsuforum = M.mod_hsuforum || {};
